name: example
description: "A new Flutter project."
publish_to: "none"

environment:
  sdk: ^3.7.2

dependencies:
  llm_toolkit:
    path: ../
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
dependency_overrides:
  llama_cpp_dart:
    git:
      url: https://github.com/netdur/llama_cpp_dart.git
      ref: main
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
