name: llm_toolkit
description: "A comprehensive Flutter SDK for running Large Language Models (LLMs) locally on mobile and desktop devices. Supports multiple inference engines including Gemma (TFLite) and Llama (GGUF) with integrated model discovery, download, and chat capabilities."
version: 0.0.2
homepage: https://github.com/DevMaan707/llm_toolkit

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  llama_cpp_dart: ^0.0.9
  flutter_gemma: ^0.9.0
  tflite_flutter: ^0.11.0
  dio: ^5.8.0
  http: ^1.1.0
  path_provider: ^2.1.1
  #tflite_text_classification: ^0.0.2

  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0

  path: ^1.8.3
  crypto: ^3.0.3
  collection: ^1.17.0

  json_annotation: ^4.8.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
